### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by Fastidious** [lyoshenka/txt#1]
Are there install instructions somewhere? Thanks!

**Comment by lyoshenka** [comment]
I don't have anything written, but I can try to outline it for you. I have it running on [dokku](https://github.com/dokku/dokku) by just pushing it. I think this may be possible on Heroku as well, since dokku is mostly a clone of Heroku. You need Redis installed, and you should use SSL (I use LetsEncrypt. idk if that works with Heroku).

Give it a try and let me know if you run into issues. I'll try to help.

**Comment by alidz1982** [comment]
how install it in xampp ?
